// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/users.proto

package grpc_golang_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcGolangAPI_GetUser_FullMethodName    = "/proto.GrpcGolangAPI/GetUser"
	GrpcGolangAPI_ListUsers_FullMethodName  = "/proto.GrpcGolangAPI/ListUsers"
	GrpcGolangAPI_CreateUser_FullMethodName = "/proto.GrpcGolangAPI/CreateUser"
)

// GrpcGolangAPIClient is the client API for GrpcGolangAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcGolangAPIClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
}

type grpcGolangAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcGolangAPIClient(cc grpc.ClientConnInterface) GrpcGolangAPIClient {
	return &grpcGolangAPIClient{cc}
}

func (c *grpcGolangAPIClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GrpcGolangAPI_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcGolangAPIClient) ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrpcGolangAPI_ServiceDesc.Streams[0], GrpcGolangAPI_ListUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, User]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrpcGolangAPI_ListUsersClient = grpc.ServerStreamingClient[User]

func (c *grpcGolangAPIClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GrpcGolangAPI_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcGolangAPIServer is the server API for GrpcGolangAPI service.
// All implementations must embed UnimplementedGrpcGolangAPIServer
// for forward compatibility.
type GrpcGolangAPIServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(*emptypb.Empty, grpc.ServerStreamingServer[User]) error
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	mustEmbedUnimplementedGrpcGolangAPIServer()
}

// UnimplementedGrpcGolangAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcGolangAPIServer struct{}

func (UnimplementedGrpcGolangAPIServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGrpcGolangAPIServer) ListUsers(*emptypb.Empty, grpc.ServerStreamingServer[User]) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedGrpcGolangAPIServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedGrpcGolangAPIServer) mustEmbedUnimplementedGrpcGolangAPIServer() {}
func (UnimplementedGrpcGolangAPIServer) testEmbeddedByValue()                       {}

// UnsafeGrpcGolangAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcGolangAPIServer will
// result in compilation errors.
type UnsafeGrpcGolangAPIServer interface {
	mustEmbedUnimplementedGrpcGolangAPIServer()
}

func RegisterGrpcGolangAPIServer(s grpc.ServiceRegistrar, srv GrpcGolangAPIServer) {
	// If the following call pancis, it indicates UnimplementedGrpcGolangAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcGolangAPI_ServiceDesc, srv)
}

func _GrpcGolangAPI_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcGolangAPIServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcGolangAPI_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcGolangAPIServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcGolangAPI_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcGolangAPIServer).ListUsers(m, &grpc.GenericServerStream[emptypb.Empty, User]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrpcGolangAPI_ListUsersServer = grpc.ServerStreamingServer[User]

func _GrpcGolangAPI_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcGolangAPIServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcGolangAPI_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcGolangAPIServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcGolangAPI_ServiceDesc is the grpc.ServiceDesc for GrpcGolangAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcGolangAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcGolangAPI",
	HandlerType: (*GrpcGolangAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GrpcGolangAPI_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _GrpcGolangAPI_CreateUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _GrpcGolangAPI_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/users.proto",
}
